config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index' 
  namespace :events do
    resources :searches, only: :index
  end
  resources :events do
    resources :comments, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  validates :text, presence: true
  has_many :comments
  belongs_to :user

  def self.search(search)
    return Event.all unless search
    Event.where('text LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments       
  has_many :events

  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to event_path(params[:event_id])  }
      format.json
    end
  end

  private
  def comment_params 
    params.require(:comment).permit(:text).merge(user_id: current_user.id, event_id: params[:event_id])
  end
end

app/controllers/events/searches_controller.rb
class Events::SearchesController < ApplicationController

  def index
    @events = Event.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  #before_action :set_event, only: [:show, :edit]
  #before_action :move_to_index, except: [:index, :show, :search]

  def index
    @events = Event.includes(:user).order("created_at DESC").page(params[:page]).per(4)
  end

  def new
    @event = Event.new
  end

  def create
    Event.create(event_params)
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
  end

  def edit
  end

  def update
    event = Event.find(params[:id])
    event.update(event_params)
  end

  def show
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  def search
    @events = Event.search(params[:keyword])
  end

  private
  def event_params
    params.require(:event).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @events = user.events.page(params[:page]).per(4).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events/searches_helper.rb
module Events::SearchesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="content_post" style="background-image: url(<%= event.image %>);">
  <div class="more">
    <i class="fa fa-edit" aria-hidden="true"></i>
    <ul class="more_list">
      <li>
        <%= link_to '詳細', "/events/#{event.id}", method: :get %>
      </li>
        <% if user_signed_in? && current_user.id == event.user_id %>
      <li>
        <%= link_to '編集', "/events/#{event.id}/edit", method: :get %>
      </li>
      <li>
        <%= link_to '削除', "/events/#{event.id}", method: :delete %>
      </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(event.text) %>
  <span class="name">
    <a href="/users/<%= event.user.id %>">
      <span>投稿者</span><%= event.user.nickname %>
    </a> 
  </span>
</div> 

app/views/events/_form.html.erb
<%= form.text_field :image, placeholder: "Image Url", id:"image" %>
<%= form.text_area :text, placeholder: "text" , rows: "10", id: "text" %>
<%= form.submit "SEND" %>

app/views/events/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/events">投稿一覧へ戻る</a>
  </div>
</div>

app/views/events/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/events/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @event, local: true) do |form| %>
      <h3>
        編集する
      </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="contents row">
  <% @events.each do |event| %>
     <%= render partial: "event", locals: { event: event } %>
  <% end %>
  <%= paginate(@events) %>
</div>

app/views/events/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @event, local: true) do |form| %>
      <h3>
        投稿する
      </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/events/search.html.erb
<%= form_with(url: search_events_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @events.each do |event| %>
    <%= render partial: "event", locals: { event: event } %>
  <% end %>
</div>

app/views/events/searches/index.html.erb
<%= form_with(url: events_searches_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @events.each do |event| %>
    <%= render partial: "events/event", locals: { event: event } %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @event.image %>);">
    <% if user_signed_in? && current_user.id == @event.user_id %> 
      <div class="more">
        <i class="fa fa-edit" aria-hidden="true"></i>
        <ul class="more_list">
          <li>
            <%= link_to '編集', "/events/#{@event.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/events/#{@event.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <% end%>
    <%= simple_format(@event.text) %>
    <span class="name">
      <a href="/users/<%= @event.user.id %>">
        <span>投稿者</span><%= @event.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@event,@comment], local: true, id: "new_comment") do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "textbox" %>
        <%= form.submit "SEND", class: "form__submit" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>

     <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My_event</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">My_event</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <%= link_to  "投稿する", "/events/new", class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright My_event 2020.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @events.each do |event| %>
    <%= render partial: "events/event", locals: { event: event } %>
  <% end %>
  <%= paginate(@events) %>
</div>